char *drivers_descriptionj[] ={
		"バラデューク (set 1)",
		"バラデューク (set 2)",
		"ボムビー",
		"ボスコニアン (Midway new ver)",
		"ボスコニアン (Midway old ver)",
		"ボスコニアン (new ver)",
		"ボスコニアン (old ver)",
		"ボスコニアン (older ver)",
		"キューティーQ",
		"ディグダグ (Atari rev 1)",
		"ディグダグ (Atari rev 2)",
		"ディグダグ (rev 1)",
		"ディグダグ (rev 2)",
		"ディグダグII (new ver)",
		"ディグダグII (old ver)",
		"ドラゴンバスター",
		"ギャラガ (Midway set 1)",
		"ギャラガ (Midway set 2)",
		"ギャラガ (Namco rev B)",
		"ギャラガ (Namco)",
		"ギャプラス / Galaga 3 (rev C)",
		"ギャプラス / Galaga 3 (set 2)",
		"ギャプラス / Galaga 3 (set 3)",
		"ギャラクシアン (Midway)",
		"ギャラクシアン (Midway old rev)",
		"ギャラクシアン (Namco set 1)",
		"ギャラクシアン (Namco set 2)",
		"ギャプラス (alt hardware)",
		"ギャプラス (rev B)",
		"ギャプラス (rev D)",
		"ジービー",
		"ジービー (Gremlin)",
		"源平討魔伝",
		"グロブダー (new ver)",
		"グロブダー (old ver set 1)",
		"グロブダー (old ver set 2)",
		"ホッピングマッピー",
		"海底宝探し",
		"キング&バルーン (日本版)",
		"キング&バルーン (USA版)",
		"マッピー (日本版)",
		"マッピー (USA版)",
		"メトロクロス (set 1)",
		"メトロクロス (set 2)",
		"モトス",
		"ナバロン",
		"ニューラリーX",
		"パック&パル",
		"パック&パル (older)",
		"パックランド (Midway)",
		"パックランド (set 1)",
		"パックランド (set 2)",
		"パックランド (set 3)",
		"パック&パル / Pac-Man & Chomp Chomp",
		"パックマン (Midway)",
		"パックマン (Midway harder)",
		"パックマン (Midway with speedup hack)",
		"パックマン / Pac-Man Plus",
		"フォゾン (日本版)",
		"ポールポジション",
		"ポールポジション (Atari ver 1)",
		"ポールポジション (Atari ver 2)",
		"ポールポジションII",
		"ポールポジションII (Atari)",
		"パックマン (日本版 set 1 with speedup hack)",
		"パックマン (日本版 set 1 Probably Bootleg)",
		"パックマン (日本版 set 2)",
		"パックマン (日本版 set 3)",
		"ラリーX",
		"ラリーX (Midway)",
		"ローリングサンダー (new ver)",
		"ローリングサンダー (old ver)",
		"スカイキッド (CUS60 ver)",
		"スカイキッド (new ver)",
		"スカイキッド (old ver)",
		"スカイキッドDX (set 1)",
		"スカイキッドDX (set 2)",
		"SOS",
		"スーパーパックマン",
		"スーパーパックマン (Midway)",
		"スーパーゼビウス",
		"タンクバタリアン",
		"イシターの復活",
		"ドルアーガの塔 (new ver)",
		"ドルアーガの塔 (old ver)",
		"ワープ&ワープ",
		"ワープ&ワープ (Rock-ola set 1)",
		"ワープ&ワープ (Rock-ola set 2)",
		"ワンダーモモ",
		"ゼビウス (Atari set 1)",
		"ゼビウス (Atari set 2)",
		"ゼビウス (Atari set 3)",
		"ゼビウス (Namco)",
		0
	};
