char *drivers_descriptionj[] ={
"ＡＳＯ -Armored Scrum Object / Alpha Mission",
"ＡＳＯ -Armored Scrum Object",
"アテナ",
"ベースボールスター -めざせ三冠王！！ / Baseball Stars -Be a champ! (PlayChoice-10)",
"ビーストバスターズ (海外版?)",
"バミューダトライアングル (日本版 old ver)",
"バミューダトライアングル (日本版)",
"バミューダトライアングル (USA版 older ver)",
"武力ＯＮＥ -World Grapple Tournament '99 in Tokyo (rev B)",
"航空騎兵物語 -The Legend of Air Cavalry / Chopper I (USA版 set 1)",
"航空騎兵物語 -The Legend of Air Cavalry / Chopper I (USA版 set 2)",
"航空騎兵物語 -The Legend of Air Cavalry / Chopper I (USA版 set 3)",
"ファイティングゴルフ / Country Club",
"脱獄 -Prisoners of War (日本版)",
"怒号層圏",
"ファンタジー (日本版)",
"ファンタジー (USA版)",
"ファンタジー (海外版)",
"餓狼伝説 -ワイルドアンビション (rev A)",
"ファイティングゴルフ (USA版)",
"ファイティングゴルフ (海外版?)",
"ファイティングサッカー",
"原始島 -１９３０’ｓ",
"グラディエイター",
"ゴールドメダリスト",
"ゴールドメダリスト (alt)",
"ゲバラ / Guerrilla War (USA版)",
"ゲバラ / Guerrilla War (ver 1)",
"ゲバラ (日本版)",
"ハル２１",
"ハル２１ (日本版)",
"怒 (日本版)",
"怒III -The Rescue",
"怒 / Ikari Warriors (USA版)",
"ジョイフルロード (日本版)",
"ジャンピングクロス",
"航空騎兵物語 -The Legend of Air Cavalry (日本版)",
"ラッソ\",
"マッドクラッシャー",
"マージャンブロック ジャンボウ (日本版)",
"メインイベント",
"マービンズメイズ",
"メカナイズドアタック (海外版)",
"名人戦",
"ジョイフルロード / Munch Mobile (USA版)",
"オズマウォーズ (set 1)",
"オズマウォーズ (set 2)",
"脱獄 -Prisoners of War / P.O.W. -Prisoners of War (USA版)",
"パドルマニア",
"パイオニアバルーン",
"原始島 -１９３０’ｓ / Prehistoric Isle in 1930 (USA版)",
"原始島 -１９３０’ｓ / Prehistoric Isle in 1930 (海外版)",
"サイコソ\ルジャー (日本版)",
"サイコソ\ルジャー (USA版)",
"ラウンドトリップＲＶ (rev B)",
"サファリラリー (日本版)",
"侍魂２ <サムライスピリッツ２> -アスラ斬魔伝",
"ＳＡＲ -サーチアンドレスキュー (USA版)",
"ＳＡＲ -サーチアンドレスキュー (海外版)",
"サスケＶＳコマンダ",
"サタンオブサターン",
"ストリートスマート (日本版 ver 1)",
"ストリートスマート (USA版 ver 1)",
"ストリートスマート (USA版 ver 2)",
"ストリートスマート (海外版 ver 1)",
"Ｔ．Ａ．Ｎ．Ｋ (日本版)",
"Ｔ．Ａ．Ｎ．Ｋ / TNK III (USA版)",
"ザ・ネクストスペース",
"タッチダウンフィーバー",
"タッチダウンフィーバー (日本版)",
"タッチダウンフィーバーII",
"ヴァンガード (Centuri)",
"ヴァンガード (日本版)",
"ヴァンガード (SNK)",
"ヴァンガードII",
"怒号層圏 / Victory Road",
"ワールドウォーズ (海外版)",
"サタンオブサターン / Zarzon",
0,
};
